source 'https://rubygems.org'
ruby '2.2.0'
gem 'rails', '4.2.3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'geocoder', '~> 1.2.7'
gem 'scoped_search', '~> 3.2.1'
gem 'draper', '~> 2.1.0'
gem 'dragonfly', '~> 1.0.11'
gem 'font-awesome-rails', '~> 4.4.0.0'
gem 'bootstrap-social-rails', '~> 4.8.0'
gem 'rabl', '~> 0.11.6'
gem 'oj', '~> 2.12.14'
gem 'rails-backbone', '~> 1.2.0'

gem 'devise'
gem 'devise-i18n'
gem 'figaro', '>= 1.0.0.rc1'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'haml-rails'
gem 'mysql2'
gem 'pundit'
gem 'simple_form'
# gem 'upmin-admin'
gem 'active_link_to', '~> 1.0.3'
gem 'kaminari'
gem 'redactor-rails', '~> 0.5.0'

group :development do
  gem 'better_errors'
  gem 'capistrano', '~> 3.0.1'
  gem 'capistrano-bundler'
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-rails-console'
  gem 'capistrano-rvm', '~> 0.1.1'
  gem 'html2haml'
  gem 'hub', :require=>nil
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
end
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails'
  gem 'rubocop'
end
group :production do
  gem 'unicorn'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end
