# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcb0b78cb0927f3d288adf6875e2236d980590c2ca8c8267495cef71c4bb1c74e65f833f373aeee0d9302543a1d443c5974198999e5c08c85847e9684244cc0a

test:
  secret_key_base: 277e1bae889c9086b5dbd33cf9b52d468bc08b2177c5965cd82b154225efd0fef0800fde13b9e3d91f78a592744a576042fb835873abb425f0420a4e6061a94b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
